apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: {{ .Values.mariadb.pvSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/db_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.mariadb.pvSize }}
  accessModes:
    - ReadWriteOnce

