apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.dbSecret.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.dbSecret.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.dbSecret.MYSQL_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.dbSecret.MYSQL_DATABASE }}

